### ISSUE TITLE
Isso tem cara de problema de validação da aplicação, ou será só zoeira?

### ISSUE THREAD

**Issue by barbosaadriano** [alissonhs/JavaFX-MVC-PROG3#14]
https://github.com/alissonhs/JavaFX-MVC-PROG3/blob/a8e6a0b7402d09376092d4b8923de12944c2eff0/Banco/banco.sql#L43

**Comment by alissonhs** [comment]
Apenas testes, de inserção de usuário que foram esquecidos de ser removidos!
Porém já foram resolvidos.
